name: c++ tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: GITHUB_REPOSITORY,GITHUB_SHA
          script: |
            echo "cloning https://github.com/${GITHUB_REPOSITORY} to /tmp/${GITHUB_SHA}"
            cd /tmp/
            git clone https://github.com/$GITHUB_REPOSITORY.git $GITHUB_SHA
            cd $GITHUB_SHA
            git checkout $GITHUB_SHA
            cmake -H. -Bbuild
            make -C build
            pushd build/test/bin/
            ./tests
            popd
          script_stop: true
